### ISSUE TITLE
correctly configuring babel-plugin-lodash to cut 400k+ from the bundle 

### ISSUE THREAD

**Issue by krnsk0** [react-boilerplate/react-boilerplate#2787]
**Is your feature request related to a problem? Please describe.**
When researching the large bundle size this boilerplate produces (following up on https://github.com/react-boilerplate/react-boilerplate/issues/918) I discovered that [babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash) is not in fact functioning as expected despite being installed, as all 527k of lodash is included in the bundle. 

After doing `npm run analyze`, I uploaded `stats.json` to [Webpack Visualizer](https://chrisbateman.github.io/webpack-visualizer/). This gets us the following: 

<img width="537" alt="Screen Shot 2019-10-23 at 2 37 18 PM" src="https://user-images.githubusercontent.com/2043026/67423745-ce876e80-f5a2-11e9-832c-077937bbc652.png">

The plugin doesn't seem to be doing anything. 

**Describe the solution you'd like**
I was able to fix this by moving the line pulling the plugin in `babel.config.js` from `env.production` to the higher-level `plugins` array. See [here](https://github.com/react-boilerplate/react-boilerplate/compare/master...krnsk0:patch-1). Bundle analysis shows this cuts the size of lodash in the bundle, as expected, indicating that tree-shaking is taking place: 

<img width="526" alt="Screen Shot 2019-10-23 at 2 42 36 PM" src="https://user-images.githubusercontent.com/2043026/67424085-7866fb00-f5a3-11e9-96d0-d0653d19a148.png">
 
**Describe alternatives you've considered**
The downside to using this plugin to make tree-shaking lodash compatible with the DX we've come to expect from React-boilerplate (`import _ from 'lodash'` is awfully convenient!) is that method-chaining in lodash becomes impossible. But this is, depending on whom one asks, [an anti-pattern](https://medium.com/making-internets/why-using-chain-is-a-mistake-9bc1f80d51ba). 

**Additional context**

**Comment by julienben** [comment]
Thank you very much for reporting this @krnsk0!

I've run the same test on my side and saw the same results in the Webpack Visualizer. However, I believe this is an error with the `analyze` script rather than with the `babel` config.  I say this because the files output by `npm run build` are the exact same, no matter where the `lodash` plugin is added.

![image](https://user-images.githubusercontent.com/8948127/67574159-9b7be100-f742-11e9-8103-248891e0874d.png)

Also, as you can see above, `npm.lodash.5baf8e1f1923b03979d3.chunk.js` is a 9.25KB file (and not 400 or 500+KB).

WDYT?

**Comment by krnsk0** [comment]
Aha-- yup, it does indeed seem to be the analyze script. In addition to confirming your result on my end, I tried pulling in some lodash functions via `import _` and the `_.` notation before `npm run build` and it does seem that only the functions which actually get used are being pulled in. 

Look like the analyze script uses webpack's `--profile` flag; can dig in to this more later.

**Comment by krnsk0** [comment]
So it looks like when `analyze.js` shells out to call webpack with the `--profile` flag it's not setting `NODE_ENV` to `production`, despite calling webpack with a reference to the production config file. Adding `cross-env NODE_ENV=production` to the beginning of the command run by `analyze.js` solves this.

This also, I think, explains why I was able to get the analysis script to (apparently) show me results when moving the plugin reference up a level (so it would run no matter what that environment variable is set to). 

If correct, changing `analyze.js` as described should solve this, I think?

**Comment by julienben** [comment]
Great catch!

We should remove the `--profile` flag as it doesn't serve any purpose in this script but also add `cross-env NODE_ENV=production` to the command (because removing `--profile` doesn't fix the issue by itself).

Would you like to open a PR to fix this?

**Comment by krnsk0** [comment]
Ah, yeah, I guess we probably don't care as much about speed as we do bundle weight here so running without the profile flag is fine. For sure, I'll put in a PR with these changes!

**Comment by julienben** [comment]
Closing this as we're about to merge the fix in #2794. Thanks again @krnsk0!

**Comment by krnsk0** [comment]
👍

**Comment by julienben** [comment]
Oops thanks for closing it.

**Comment by julienben** [comment]
Oops thanks for closing it.
